# Site Domain URL
baseurl 					= "https://youtuberis.lt"
# Site Data
title 						= "Youtuberis"
# Site Render Folder
publishDir 					= "docs"
# Language code for RSS Feed
languageCode 				= "lt-LT"
# Disqus Comments Shortname
disqusShortname 			= "youtuberis"
# Disable Hugo Generator meta tag in head
disableHugoGeneratorInject 	= true

[params]
	copyrightL				= "Sukurta su <b-icon icon=\"heart\" size=\"is-small\"></b-icon>"
	copyrightR				= "&copy; 2018 YouTube Draugas | Lukas Vanagas"
[taxonomies]
	kategorija 	= "kategorijos"
	tema 		= "temos"

[permalinks]
	post = "/:slug/"
	page = "/:slug/"
	duk  = "/duk/:slug/"

[blackfriday]
	plainIDAnchors 	= true
	hrefTargetBlank = true
	angledQuotes 	= false
	latexDashes 	= true
	extensions 		= ['github_flavored_markdown']

menu = ["main"]

[[menu.main]]
		name 	= "Žaidimų monetizacija"
		pre 	= ""
		weight 	= 10
		url 	= "/zaidimu-monetizacijos-informacija/"

[[menu.main]]
		name 	= "Muzika"
		pre 	= ""
		weight 	= 12
		url 	= "/muzika/"

[[menu.main]]
		name 	= "Medija"
		pre 	= ""
		weight 	= 14
		url 	= "/juosta/"