# Site Domain URL
baseurl 					= "https://www.youtuberis.lt/"
# Site Data
title 						= "Youtuberis"
# Site Render Folder
publishDir 					= "docs"
# Language code for RSS Feed
languageCode 				= "lt-LT"
# Disqus Comments Shortname
disqusShortname 			= "youtuberis"
# Disable Hugo Generator meta tag in head
disableHugoGeneratorInject 	= true
# Hugo default Robots.txt file generation
enableRobotsTXT				= true
# Bind with Git Repo for data reporting
enableGitInfo				= true

[params]
	copyrightL	= "Sukurta su 🍌"
	copyrightR	= "&copy; 2018 Lukas Vanagas"
	# Branding Logo URLs
	logoPNG_60	= "/img/brand@60px.png"
	logoPNG_112	= "/img/brand@112px.png"
	logoPNG_24	= "/img/brand.png"
	logoSVG		= "/img/brand.svg"
	# Date format when generating JSON-LD
	ISO8601 	= "2006-01-02T15:04:05JST"
	# Schema information
	author		= "Lukas Vanagas"

	# Description of site
	Description = "Labas, aš Lukas. Jau keletą metų domiuos YouTube, temomis kaip tai veikia, kaip uždarbiauti. O, kad tavo kelias būtų lengvesnis, čia savo žiniomis dalinuosi su tavimi."
	
[taxonomies]
	kategorija 	= "kategorijos"
	tema 		= "temos"

[permalinks]
	post = "/:slug/"
	page = "/:slug/"
	duk  = "/duk/:slug/"

[blackfriday]
	plainIDAnchors 	= true
	hrefTargetBlank = true
	angledQuotes 	= false
	latexDashes 	= true
	extensions 		= ['github_flavored_markdown']

menu = ["main"]

[[menu.main]]
		name 	= "Žaidimų monetizacija"
		pre 	= ""
		weight 	= "10"
		url 	= "/zaidimu-monetizacijos-informacija/"

[[menu.main]]
		name 	= "Muzika"
		pre 	= ""
		weight 	= "12"
		url 	= "/muzika/"

[[menu.main]]
		name 	= "Medija"
		pre 	= ""
		weight 	= "14"
		url 	= "/juosta/"