# Site Domain URL
baseurl 					= "https://example.com"
# Site Data
title 						= "YouTube Draugas"
copyright 					= "&copy; 2017 YouTube Draugas | Lukas Vanagas"
# Site Render Folder
publishDir 					= "docs"
# Language code for RSS Feed
languageCode 				= "lt-LT"
# Disqus Comments Shortname
disqusShortname 			= "demo"
# Disable Hugo Generator meta tag in head
disableHugoGeneratorInject 	= true

[params]
	disqusPublicKey			= "Wkz5FMpf1QxScQY4UIExLxTWo64z61Sf5EJtFLVi2QINZuLo0GwOzmzez0q3kKDv"
[taxonomies]
	kategorija 	= "kategorijos"
	tema 		= "temos"

[permalinks]
	post = "/:slug/"
	page = "/:slug/"
	duk  = "/duk/:slug/"

[blackfriday]
	plainIDAnchors 	= true
	hrefTargetBlank = true
	angledQuotes 	= false
	latexDashes 	= true
	extensions 		= ['github_flavored_markdown']

menu = ["main"]

[[menu.main]]
		name 	= "Žaidimų monetizacija"
		pre 	= ""
		weight 	= 10
		url 	= "/zaidimu-monetizacijos-informacija/"

[[menu.main]]
		name 	= "Muzika"
		pre 	= ""
		weight 	= 12
		url 	= "/muzika/"

[[menu.main]]
		name 	= "Medija"
		pre 	= ""
		weight 	= 14
		url 	= "/juosta/"