baseurl = "https://example.com"
languageCode = "lt-LT"
title = "YouTube Draugas"
copyright = "&copy; YouTube Draugas 2017"
disqusShortname = "demo"
disableHugoGeneratorInject = true

[params]
	sloganImageUrl = "/img/skeleton/sidenav-bg.jpg"
	slogan = "Atrask daugiau, tapk draugu!"
	author = "Lukas"
	description = "YouTube pasaulio naujienos, patarimai, pagalba ir ištekliai. Dažniausiai užduodami klausimai."


[taxonomies]
	category = "categories"
	tag = "tags"

[permalinks]
	post = "/:slug/"
	# page = "/:slug/"
	duk  = "/duk/:slug/"

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
	angledQuotes = false
	latexDashes = true
	extensions = ['github_flavored_markdown']

menu = ["main"]

[[menu.main]]
		name = "Resources"
		pre = "book"
		weight = 10
		url = "#"

[[menu.main]]
		name = "Placeholder"
		pre = "book"
		weight = 14
		url = "#"

[[menu.main]]
		name = "LandingPage"
		pre = "book"
		weight = 16
		url = "#"