backend:
  site_domain: "cms.youtuberis.lt"
  name: git-gateway
  branch: master

media_folder: "src/images"
public_folder: "/img"

display_url: https://www.youtuberis.lt

collections: 

  - name: "posts"
    label: "Įrašai"
    label_singular: "Įrašas"
    folder: "content/post"
    create: true
    slug: "{{day}}/{{month}}-{{year}}_{{slug}}"
    fields:
    - label: "Pavadinimas"
      name: "title"
      widget: "string"
    
    - label: "Nuoroda"
      name: slug
      widget: "string"
      default: "{{slug}}"

    - label: "Aprašymas"
      name: "description"
      widget: "text"
      required: false

    - label: "Antraštė"
      name: "subtitle"
      widget: "string"

    - label: "Turinys"
      name: "body"
      widget: "markdown"
      
    - label: "Nuotraukos"
      name: "images"
      widget: "list"
      allow_add: true

    - label: "Kategorijos"
      name: "kategorijos"
      widget: "list"
      allow_add: true
      field: 
        - label: "Nuotraukos URL"
          name: "url"
          widget: "string"

      # Currently not used by website
    - label: "temos"
      name: "temos"
      widget: "hidden"
      allow_add: true

    - label:  "Juodraštis"
      name: "draft"
      widget: "boolean"
      default: true

    - label: "Komentarai"
      name: "comments"
      widget: "boolean"
      default: true

    - label: "ID (neredaguoti)"
      name: "disqus_identifier"
      widget: "datetime"
      format: "X"

